import unittest
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine_core import GameState, Player, Action
from fast_evaluator import FastEvaluator

class TestPayouts(unittest.TestCase):
    def setUp(self):
        self.game = GameState(n_players=3)
        self.game.reset()
        # Clear bets generated by reset() to have a clean slate for manual tests
        for p in self.game.players:
            p.bet = 0
            p.total_bet = 0
        self.game.pot = 0

    def test_simple_winner(self):
        # P0 bets 100, P1 calls 100, P2 folds.
        # Board: A K Q J T (Royal on board? No, let's just give P0 a royal)
        
        # P0: As Ks
        self.game.players[0].hand = [51, 50] 
        # P1: 2c 3c
        self.game.players[1].hand = [0, 1]
        
        # Board: Qs Js Ts 2d 3d
        self.game.board = [49, 48, 47, 13, 14]
        
        # Pot
        self.game.pot = 200
        self.game.players[0].total_bet = 100
        self.game.players[1].total_bet = 100
        self.game.players[2].active = False
        
        payouts = self.game.resolve_hand()
        
        self.assertEqual(payouts[0], 200)
        self.assertEqual(payouts[1], 0)

    def test_split_pot(self):
        # P0 and P1 have same hand (Board plays)
        # Board: As Ks Qs Js Ts (Royal on Board)
        self.game.board = [51, 50, 49, 48, 47]
        self.game.players[0].hand = [0, 1]
        self.game.players[1].hand = [2, 3]
        
        self.game.pot = 200
        self.game.players[0].total_bet = 100
        self.game.players[1].total_bet = 100
        self.game.players[2].active = False
        
        payouts = self.game.resolve_hand()
        
        self.assertEqual(payouts[0], 100)
        self.assertEqual(payouts[1], 100)

    def test_side_pot(self):
        # P0 All-in for 10
        # P1 Bets 100
        # P2 Calls 100
        
        # Pot Total = 10 + 100 + 100 = 210
        # Main Pot = 10 + 10 + 10 = 30 (Eligible: P0, P1, P2)
        # Side Pot = 0 + 90 + 90 = 180 (Eligible: P1, P2)
        
        self.game.players[0].total_bet = 10
        self.game.players[0].all_in = True
        self.game.players[1].total_bet = 100
        self.game.players[2].total_bet = 100
        self.game.pot = 210
        
        # Rank: P0 (Best) > P1 (Middle) > P2 (Worst)
        # P0 wins Main (30).
        # P1 wins Side (180).
        # P0 Total = 30. P1 Total = 180.
        
        # Setup Hands implies ranks
        
        # Board: 2c 3c 4c 5c 7d (No straight flush, keep it simple)
        self.game.board = [0, 1, 2, 3, 18]
        
        # P0: As Ah (Aces) -> Best
        self.game.players[0].hand = [51, 38]
        
        # P1: Ks Kh (Kings) -> Second
        self.game.players[1].hand = [50, 37]
        
        # P2: Qs Qh (Queens) -> Third
        self.game.players[2].hand = [49, 36]
        
        payouts = self.game.resolve_hand()
        
        self.assertEqual(payouts[0], 30)
        self.assertEqual(payouts[1], 180)
        self.assertEqual(payouts[2], 0)

if __name__ == '__main__':
    unittest.main()
